# AetherOS Hyprland baseline

monitor=,preferred,auto,1

$terminal = foot
$menu = fuzzel
$browser = xdg-open https://localhost

exec-once = waybar
exec-once = /home/miqua/Desktop/AetherOS/bin/aether-up
exec-once = foot --app-id aether-shell -e /home/miqua/Desktop/AetherOS/bin/aether-status
exec-once = foot --app-id aether-operator -e /home/miqua/Desktop/AetherOS/bin/aether-operator

general {
    gaps_in = 6
    gaps_out = 16
    border_size = 2
    col.active_border = rgba(93c5fdff)
    col.inactive_border = rgba(2e344099)
    layout = dwindle
}

decoration {
    rounding = 10
    blur {
        enabled = true
        size = 4
        passes = 2
    }
}

input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = true
    }
}

bind = SUPER, Return, exec, $terminal
bind = SUPER, D, exec, $menu
bind = SUPER, S, exec, /home/miqua/Desktop/AetherOS/bin/aether-screenshot
bind = SUPER, A, exec, foot -e /home/miqua/Desktop/AetherOS/bin/aether-status
bind = SUPER, O, exec, foot -e /home/miqua/Desktop/AetherOS/bin/aether-operator
bind = SUPER, R, exec, foot -e /home/miqua/Desktop/AetherOS/bin/aether-recover
bind = SUPER SHIFT, U, exec, foot -e /home/miqua/Desktop/AetherOS/bin/aether-up
bind = SUPER SHIFT, D, exec, foot -e /home/miqua/Desktop/AetherOS/bin/aether-down
bind = SUPER SHIFT, A, exec, foot -e curl -s http://127.0.0.1:8011/status
bind = SUPER, Q, killactive,
bind = SUPER SHIFT, E, exit,

windowrulev2 = float,class:^(aether-shell)$
